name: Gradle build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # java: [8, 9, 10, 11, 12]
        java: [8, 11]
        gradle: [6.1, 6.0.1, 5.6.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1.2.0
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle Wrapper
        run: gradle wrapper --gradle-version ${{ matrix.gradle }} --distribution-type bin
      - name: Build Plugin
        run: ./gradlew :plugin:build --stacktrace