name: Samples - Boost

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Assemble:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare samples
        working-directory: samples
        run: gradle
      - name: Download upstream source code
        working-directory: samples
        run: gradle :downloadUpstream
      - name: List all tasks which will run
        working-directory: samples
        run: gradle :assembleAllCompatibleModules -m
      - name: Assemble all passing modules
        working-directory: samples
        run: gradle --info :assembleAllCompatibleModules
  Quaranteened:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set up JDK
        uses: actions/setup-java@v1.2.0
        with:
          java-version: 11
      - name: Prepare samples
        working-directory: samples
        run: gradle
      - name: Download upstream source code
        working-directory: samples
        run: gradle :downloadUpstream
      - name: List all tasks which will run
        working-directory: samples
        run: gradle :assembleAllQuarantinedModules -m
      - name: Assemble all quarantined modules
        working-directory: samples
        run: gradle --info --continue :assembleAllQuarantinedModules || exit 0