name: Samples - Boost

on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline

jobs:
  Assemble:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare boost sample
        working-directory: samples
        run: gradle
      - name: Download boost from upstream
        working-directory: samples
        run: gradle :boost:downloadUpstream
      - name: List all tasks which will run
        working-directory: samples
        run: gradle :boost:assembleAllCompatibleModules -m
      - name: Assemble all passing modules
        working-directory: samples
        run: gradle --info :boost:assembleAllCompatibleModules
  Quaranteened:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set up JDK
        uses: actions/setup-java@v1.2.0
        with:
          java-version: 11
      - name: Prepare boost sample
        working-directory: samples
        run: gradle
      - name: Download boost from upstream
        working-directory: samples
        run: gradle :boost:downloadUpstream
      - name: List all tasks which will run
        working-directory: samples
        run: gradle :boost:assembleAllQuarantinedModules -m
      - name: Assemble all quarantined modules
        working-directory: samples
        run: gradle --info --continue :boost:assembleAllQuarantinedModules || exit 0